service: ystromm-shiny-forthnight-cicd

custom:
  repository: https://github.com/ystromm/shiny-forthnight

provider:
  name: aws
  stage: prod
  region: eu-north-1

resources:
  Resources:
    ECRRepository:
      Type: AWS::ECR::Repository
      Properties:
         RepositoryName: ystromm/shiny-forthnight

    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ystromm-shiny-forthnight

    BuildCodeBuildProject:
      Type: AWS::CodeBuild::Project
      DependsOn: CodeBuildRole
      Properties:
        Artifacts:
          Type: no_artifacts
        Environment:
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/standard:5.0
          Type: LINUX_CONTAINER
          PrivilegedMode: true
        Name: ${self:service}-Build
        ServiceRole:
          Ref: CodeBuildRole
        Source:
          Type: GITHUB
          BuildSpec: cicd/buildspec.yml
          Auth:
            Type: OAUTH
          Location: ${self:custom.repository}
#        Triggers:
#          Webhook: true
#          FilterGroups:
#            - - Pattern: ^refs/heads/master
#                Type: HEAD_REF
#              - Pattern: PUSH
#                Type: EVENT

    CodeBuildRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-CodeBuildRole-${self:provider.region}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Principal:
                Service:
                  - codebuild.amazonaws.com
        Path: "/"
        Policies:
          - PolicyName: ${self:service}-CodeBuildCodeBuildPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - codebuild:*
                  Resource:
                    - "*"
          - PolicyName: ${self:service}-CodeBuildLogsPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:*
                  Resource:
                    - "*"
